# Generated by Django 5.0.1 on 2024-01-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_background_img_contact_statistics_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_model',
        ),
    ]
