# Generated by Django 5.0.1 on 2024-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_info_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='background_img',
            name='img2',
            field=models.ImageField(default=1, upload_to='bg/'),
            preserve_default=False,
        ),
    ]
