# Generated by Django 5.0.1 on 2024-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='phone_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
