# Generated by Django 5.0.1 on 2024-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_info_phone_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
            ],
        ),
    ]
