# Generated by Django 5.0.1 on 2024-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_telegram_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(upload_to='programmers/'),
        ),
    ]
