# Generated by Django 5.0.1 on 2024-01-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_teammember_github_teammember_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='programmers/')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('github', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='github',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='text',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(upload_to='team_members'),
        ),
    ]
