# Generated by Django 5.0.1 on 2024-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_programmer_remove_teammember_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idea', models.TextField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
