# Generated by Django 5.0.1 on 2024-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_client2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client2',
            name='job',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
